function preparedDataset = prepare_data_additional()
    %% Input dataset
    
    % 10% dataset
    dataset = readtable("bank-additional.csv");
    
    % Full dataset
    % dataset = readtable("bank-additional-full.csv");
    
    % Check missing values
    missing = ismissing(dataset);
    rowsWithMissing = dataset(any(missing,2),:);
    % disp(rowsWithMissing)
    
    % Remove row with unknown value ???
    
    dataset.job = categorical(dataset.job);
    dataset.marital = categorical(dataset.marital);
    dataset.education  = categorical(dataset.education, ...
        {'unknown', 'basic.4y', 'basic.6y', 'basic.9y', ...
        'high.school', 'illiterate', 'professional.course', 'university.degree'}, 'Ordinal',true);
    dataset.default = categorical(dataset.default);
    dataset.housing = categorical(dataset.housing);
    dataset.loan = categorical(dataset.loan);
    dataset.contact = categorical(dataset.contact);
    dataset.day_of_week = categorical(dataset.day_of_week);
    dataset.month = categorical(dataset.month);
    dataset.poutcome = categorical(dataset.poutcome);
    dataset.y = categorical(dataset.y);
    
    %% Feature encoding
        
    % one hot encoding
    oneHotTable = table();
    oneHotTable = [generate_onehot_table(dataset.job, 'job') ...
        generate_onehot_table(dataset.marital, 'marital') ...
        generate_onehot_table(dataset.default, 'default') ...
        generate_onehot_table(dataset.housing, 'housing') ...
        generate_onehot_table(dataset.loan, 'loan') ...
        generate_onehot_table(dataset.contact, 'contact') ...
        generate_onehot_table(dataset.day_of_week, 'day_of_week') ...
        generate_onehot_table(dataset.month, 'month') ...
        generate_onehot_table(dataset.poutcome, 'poutcome') ...
        ];
        
    % label encoding
    labelEncTable = table(double(dataset.education),'VariableNames',{'education'});
    
    % one hot output
    oneHotOutputTable = [generate_onehot_table(dataset.y, 'y')];
    
    % all encoded dataset
    encodedCatDataset = [oneHotTable labelEncTable oneHotOutputTable];
        
    % prepared dataset
    preparedDataset = [table(dataset.age,'VariableNames',{'age'}) ...
        table(dataset.duration, 'VariableNames',{'duration'}) ...
        table(dataset.campaign, 'VariableNames',{'campaign'}) ...
        table(dataset.pdays, 'VariableNames', {'pdays'}) ...
        table(dataset.previous, 'VariableNames',{'previous'}) ...
        table(dataset.emp_var_rate, 'VariableNames',{'emp_var_rate'}) ...
        table(dataset.cons_price_idx, 'VariableNames',{'cons_price_idx'}) ...
        table(dataset.cons_conf_idx, 'VariableNames',{'cons_conf_idx'}) ...
        table(dataset.euribor3m, 'VariableNames',{'euribor3m'}) ...
        table(dataset.nr_employed, 'VariableNames',{'nr_employed'}) ...
        encodedCatDataset];
end